apiVersion: apps/v1
kind: Deployment
metadata:
  name: abcd-fe-deployment
  labels:
    app: abcd-fe
spec:
  replicas: 2
  selector:
    matchLabels:
      app: abcd-fe
  template:
    metadata:
      labels:
        app: abcd-fe
    spec:
      containers:
      - name: abcd-fe-container
        # ⚠️ 이미지 주소는 깃허브 아이디 소문자 규격(cubickim)과 새 프로젝트명(abcd_fe)을 반영합니다.
        image: ghcr.io/cubickim/abcd_fe:10
        ports:
        - containerPort: 8080