apiVersion: v1
kind: Service
metadata:
  name: abcd-ppp-service
spec:
  type: NodePort # 외부 내 PC 브라우저에서 접근할 수 있도록 문을 열어주는 타입
  selector:
    app: abcd-ppp # 위의 deployment.yaml에 적은 app 이름과 똑같이 맞춰서 연결합니다.
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 31000 # 내 PC 브라우저에서 http://localhost:31000 으로 접속하겠다는 의미