apiVersion: apps/v1
kind: Deployment
metadata:
  name: abcd-db
  labels:
    app: abcd-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: abcd-db
  template:
    metadata:
      labels:
        app: abcd-db
    spec:
      containers:
      - name: postgres
        image: postgres:15
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          value: "abcd_db"
        - name: POSTGRES_PASSWORD
          value: "cubicinc"
---
apiVersion: v1
kind: Service
metadata:
  name: abcd-db-service # 이름은 기존과 똑같이 유지해서 백엔드가 그대로 바라볼 수 있게 합니다.
spec:
  type: ClusterIP # 외부망(ExternalName)을 버리고, 쿠버네티스 내부 전용망으로 변경합니다.
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    app: abcd-db