apiVersion: v1
kind: Service
metadata:
  name: abcd-be-service # 🎯 내부 연동의 핵심 열쇠가 될 이름입니다!
spec:
  type: ClusterIP # 백엔드는 외부 노출이 필요 없으므로 내부 전용(ClusterIP)으로 만듭니다.
  selector:
    app: abcd-be
  ports:
    - port: 8081
      targetPort: 8081